---

- name: Ansible AWX | Install | Installing setup-dependencies
  ansible.builtin.apt:
    name: ['build-essential', 'python3-pexpect']

- name: Ansible AWX | Install | Creating lib dir
  ansible.builtin.file:
    path: "{{ AWX_CONFIG.path }}"
    state: directory

- name: Ansible AWX | Install | Downloading awx source code
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    version: "{{ AWX_CONFIG.release }}"
    dest: "{{ AWX_CONFIG.path }}"
    depth: 1
  ignore_errors: true
  register: axw_download

- name: Ansible AWX | Install | Download failed
  ansible.builtin.fail:
    msg: 'Unable to download source-code from ansible-awx repository!'
  when:
    - axw_download.failed is defined
    - axw_download.failed
    - not awx_lib.stat.exists

# container version would always be 'latest' if not set to specific version
# venv ending-slash would result in incorrect paths inside the container
- name: Ansible AWX | Install | Makefile fixes
  ansible.builtin.lineinfile:
    path: "{{ AWX_CONFIG.path }}/Makefile"
    state: present
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
  with_items:
    - {reg: '^COMPOSE_TAG \?= \$\(GIT_BRANCH\)', line: "COMPOSE_TAG = {{ AWX_CONFIG.release }}"}
    - {reg: '^VENV_BASE \?= \/var\/lib\/awx\/venv\/', line: "VENV_BASE ?= /var/lib/awx/venv"}

# nginx not starting: https://github.com/ansible/awx/issues/9552
# runner container not working: https://github.com/ansible/awx/issues/10099
- name: Ansible AWX | Install | Fixing bugs in main container
  ansible.builtin.lineinfile:
    path: "{{ AWX_CONFIG.path }}/tools/ansible/roles/dockerfile/templates/Dockerfile.j2"
    state: present
    line: "RUN {{ item }}"
    insertbefore: 'ENTRYPOINT \["\/entrypoint\.sh"\]'
  with_items:
    - "grep -qxF 'mount_program = \"/usr/bin/fuse-overlayfs\"' /etc/containers/storage.conf ||
    sed -i '/^\\[storage.options\\]/a mount_program = \"/usr/bin/fuse-overlayfs\"' /etc/containers/storage.conf"
    - "grep -qxF 'user nobody;' /etc/nginx/nginx.conf ||
    echo 'user nobody;' >> /etc/nginx/nginx.conf"

- name: Ansible AWX | Install | Configuring settings
  ansible.builtin.template:
    src: 'templates/var/lib/ansible_awx/v/tools/docker-compose/inventory.j2'
    dest: "{{ AWX_CONFIG.path }}/tools/docker-compose/inventory"
  no_log: true

- name: Ansible AWX | Install | Preparing docker (this will take some time on the first run!)
  ansible.builtin.make:
    chdir: "{{ AWX_CONFIG.path }}"
    target: 'docker-compose-build'

- name: Ansible AWX | Install | Preparing docker ##2
  ansible.builtin.command: 'make docker-auth awx/projects docker-compose-sources'  # will not run via 'make' module because of unimportant error..
  args:
    chdir: "{{ AWX_CONFIG.path }}"
  when: AWX_CONFIG.release|float < 19.4

- name: Ansible AWX | Install | Preparing docker ##2
  ansible.builtin.make:
    chdir: "{{ AWX_CONFIG.path }}"
    target: 'make awx/projects docker-compose-sources'
  when: AWX_CONFIG.release|float >= 19.4

- name: Ansible AWX | Install | Building WebUI (this will take some time!)
  ansible.builtin.command: "docker-compose -f {{ AWX_CONFIG.path }}/tools/docker-compose/_sources/docker-compose.yml run --rm awx_1 make clean-ui ui-devel"

- name: Ansible AWX | Install | Starting service
  ansible.builtin.systemd:
    name: "{{ AWX_CONFIG.service_prefix }}ansible-awx.service"
    state: started

- name: Ansible AWX | Install | Waiting for initialization to finish (go get a coffee or tea!)
  ansible.builtin.pause:
    seconds: 300

- name: Ansible AWX | Install | Creating AWX Admin-Account via django-shell
  ansible.builtin.expect:
    command: "docker exec -it tools_awx_1 awx-manage 'createsuperuser'"
    responses:
      Username: "{{ AWX_CONFIG.admin_user }}"
      Email address: "{{ AWX_CONFIG.admin_mail }}"
      Password: "{{ AWX_CONFIG.admin_pwd }}"
      Password (again): "{{ AWX_CONFIG.admin_pwd }}"
  ignore_errors: true
  no_log: true
  register: user_creation
  when: AWX_CONFIG.admin_pwd is defined

- name: Ansible AWX | Install | User-Creation not possible
  ansible.builtin.pause:
    prompt: "You have not defined a admin password for AWX!
    You might need to run the following command to create a superuser for yourself:
    \"docker exec -it tools_awx_1 awx-manage 'createsuperuser'\""
  when: AWX_CONFIG.admin_pwd is undefined

- name: Ansible AWX | Install | User-Creation failed
  ansible.builtin.pause:
    prompt: "The AWX admin user-creation failed!
    You might need to run the following command to create a superuser for yourself:
    \"docker exec -it tools_awx_1 awx-manage 'createsuperuser'\""
  when:
    - user_creation.failed is defined
    - user_creation.failed

- name: Ansible AWX | Install | Removing setup-dependencies
  ansible.builtin.apt:
    name: 'build-essential'
    state: absent
