---

- name: Ansible AWX | Installing docker
  ansible.builtin.import_role:
    name: ansibleguy.infra_docker_minimal
  vars:
    DOCKER_COMPOSE: true

- name: Ansible AWX | Installing docker
  ansible.builtin.import_role:
    name: ansibleguy.infra_nginx
  vars:
    NGINX_CONFIG: 'proxy'
    NGINX_PROXY_PORT: 8013
    NGINX_CERT_CSR_DATA:
      country: 'AT'
      org: 'AnsibleGuy'
      email: "{{ AWX_ADMIN_MAIL }}"
      cn: "Ansible AWX"

- name: Ansible AWX | Adding ansible repository-key
  ansible.builtin.apt_key:
    keyserver: "{{ ANSIBLE_REPO_KEYSERVER }}"
    id: "{{ ANSIBLE_REPO_KEY_ID }}"

- name: Ansible AWX | Add ansible repository
  ansible.builtin.apt_repository:
    repo: "deb {{ ANSIBLE_REPO_URL }} {{ ANSIBLE_REPO_VERSION_MATCHING[ansible_distribution_release|lower] }} main"

- name: Ansible AWX | Installing ansible
  ansible.builtin.apt:
    name: 'ansible'
    state: present

- name: Ansible AWX | Adding service files
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ AWX_SERVICE_PREFIX }}{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  with_items:
    - 'ansible-awx.service'
    - 'backup-ansible-awx.service'
    - 'backup-ansible-awx.timer'

- name: Ansible AWX | Copying backup script
  ansible.builtin.template:
    src: 'templates/usr/local/sbin/backup_ansible_awx.sh.j2'
    dest: '/usr/local/sbin/backup_ansible_awx.sh'
    owner: 'root'
    group: 'root'
    mode: 0755
  when: AWX_BACKUP

- name: Ansible AWX  | Enabling/Starting backup timer
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ AWX_SERVICE_PREFIX }}backup-ansible-awx.timer"
    enabled: yes
    state: started
  when: AWX_BACKUP

- name: Ansible AWX  | Enabling startup service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ AWX_SERVICE_PREFIX }}ansible-awx.service"
    enabled: yes

- name: Ansible AWX | Checking if AWX can be found
  ansible.builtin.stat:
    path: "{{ AWX_DIR }}"
  register: awx_lib

- name: Ansible AWX | Installing
  ansible.builtin.import_tasks: install.yml
  when: >
    AWX_INSTALL or
    not awx_lib.stat.exists
